# Generated by Django 4.1.3 on 2022-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavItems',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fitemId', models.JSONField(null=True, verbose_name=models.BigIntegerField())),
            ],
        ),
    ]
